excluded:
 - Pods/
 - Carthage/
 - Crown/Resources/R.generated.swift
 - Scripts/

line_length:
- 300   # warning
- 400   # error

type_body_length:
- 400   # warning
- 600   # error

file_length:
- 400   # warning
- 1000  # error

function_body_length:
- 100   # warning
- 200   # error

opt_in_rules:
- closure_end_indentation
- contains_over_first_not_nil # kind - perfomance 
- discouraged_optional_boolean
- empty_count # kind - perfomance 
- empty_string # kind - perfomance 
- first_where # kind - perfomance 
- force_unwrapping
- literal_expression_end_indentation
- multiline_parameters
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- private_action
- redundant_nil_coalescing
- sorted_first_last # kind - perfomance 
- switch_case_on_newline
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- yoda_condition


disabled_rules:
# SwiftFormatを利用することで空白は削除できる。SwiftFormatでは'--trimwhitespace nonblank-lines'を利用し、空行のインデントを残しているので、trailing_whitespaceはdisabledにしておく
- trailing_whitespace 
- large_tuple

identifier_name:
  min_length:
    warning: 1
